// Liste des pays (noms en francais), triee alphabetiquement.
export const PAYS = [
  "Afghanistan", "Afrique du Sud", "Albanie", "Algerie", "Allemagne", "Andorre", "Angola",
  "Arabie saoudite", "Argentine", "Armenie", "Australie", "Autriche", "Azerbaidjan",
  "Bahamas", "Bahrein", "Bangladesh", "Belgique", "Belize", "Benin", "Bhoutan", "Bielorussie",
  "Birmanie", "Bolivie", "Bosnie-Herzegovine", "Botswana", "Bresil", "Brunei", "Bulgarie",
  "Burkina Faso", "Burundi",
  "Cambodge", "Cameroun", "Canada", "Cap-Vert", "Chili", "Chine", "Chypre", "Colombie",
  "Comores", "Congo-Brazzaville", "Congo-Kinshasa (RDC)", "Coree du Nord", "Coree du Sud",
  "Costa Rica", "Cote d'Ivoire", "Croatie", "Cuba",
  "Danemark", "Djibouti", "Dominique",
  "Egypte", "Emirats arabes unis", "Equateur", "Erythree", "Espagne", "Estonie", "Eswatini",
  "Etats-Unis", "Ethiopie",
  "Fidji", "Finlande", "France",
  "Gabon", "Gambie", "Georgie", "Ghana", "Grece", "Grenade", "Guatemala", "Guinee",
  "Guinee-Bissau", "Guinee equatoriale", "Guyana",
  "Haiti", "Honduras", "Hongrie",
  "Inde", "Indonesie", "Irak", "Iran", "Irlande", "Islande", "Israel", "Italie",
  "Jamaique", "Japon", "Jordanie",
  "Kazakhstan", "Kenya", "Kirghizistan", "Kiribati", "Kosovo", "Koweit",
  "Laos", "Lesotho", "Lettonie", "Liban", "Liberia", "Libye", "Liechtenstein",
  "Lituanie", "Luxembourg",
  "Macedoine du Nord", "Madagascar", "Malaisie", "Malawi", "Maldives", "Mali", "Malte",
  "Maroc", "Maurice", "Mauritanie", "Mexique", "Micronesie", "Moldavie", "Monaco",
  "Mongolie", "Montenegro", "Mozambique",
  "Namibie", "Nauru", "Nepal", "Nicaragua", "Niger", "Nigeria", "Norvege",
  "Nouvelle-Zelande",
  "Oman", "Ouganda", "Ouzbekistan",
  "Pakistan", "Palaos", "Palestine", "Panama", "Papouasie-Nouvelle-Guinee", "Paraguay",
  "Pays-Bas", "Perou", "Philippines", "Pologne", "Portugal",
  "Qatar",
  "Republique centrafricaine", "Republique dominicaine", "Republique tcheque", "Roumanie",
  "Royaume-Uni", "Russie", "Rwanda",
  "Saint-Kitts-et-Nevis", "Saint-Marin", "Saint-Vincent-et-les-Grenadines", "Sainte-Lucie",
  "Salomon", "Salvador", "Samoa", "Sao Tome-et-Principe", "Senegal", "Serbie",
  "Seychelles", "Sierra Leone", "Singapour", "Slovaquie", "Slovenie", "Somalie", "Soudan",
  "Soudan du Sud", "Sri Lanka", "Suede", "Suisse", "Suriname", "Syrie",
  "Tadjikistan", "Tanzanie", "Tchad", "Thailande", "Timor oriental", "Togo", "Tonga",
  "Trinite-et-Tobago", "Tunisie", "Turkmenistan", "Turquie", "Tuvalu",
  "Ukraine", "Uruguay",
  "Vanuatu", "Vatican", "Venezuela", "Vietnam",
  "Yemen",
  "Zambie", "Zimbabwe",
];
